
services:
  nginx:
    image: nginx:librahim
    container_name: nginx
    build: ./requirements/nginx
    ports:
      - "443:443"
    depends_on:
      - wordpress
    volumes:
      - wordpress:/var/www/wordpress
    networks:
      - incepnet
    restart: always


  mariadb:
    image: mariadb:librahim
    container_name: mariadb
    build: ./requirements/mariadb
    volumes:
      - mariadb:/var/lib/mysql
    env_file :
      - .env
    networks :
      - incepnet
    restart: always



  wordpress:
    image: wordpress:librahim
    container_name: wordpress
    build: ./requirements/wordpress
    depends_on:
      - mariadb
    volumes:
      - wordpress:/var/www/wordpress
    env_file :
      - .env
    networks:
      - incepnet
    restart: always

  adminer:
    build: requirements/bonus/adminer
    image: adminer:librahim
    container_name: adminer
    restart: always
    ports:
      - "8080:8080"
    networks:
      - incepnet
    depends_on:
      - mariadb
    
  redis:
    build: requirements/bonus/redis
    image: redis:librahim
    restart: always
    networks:
      - incepnet

  website:
    build: requirements/bonus/static_website
    image: website:librahim
    container_name: simple_website
    restart: always
    ports:
      - "4000:4000"
    networks:
      - incepnet

  cadvisor:
      build: requirements/bonus/cadvisor
      image: cadvisor:librahim
      restart: always
      container_name: cadvisor
      ports:
        - "8081:8080"

      volumes:
        - vol_one:/rootfs:ro 
        - vol_two:/var/run:ro
        - vol_thri:/sys:ro
        - vol_foor:/var/lib/docker:ro
        - vol_five:/sys/fs/cgroup:ro
        - vol_proc:/rootfs/proc:ro
      networks:
        - incepnet


volumes:
  mariadb:
    name: mariadb
    driver: local
    driver_opts:
      device: /home/librahim/data/mariadb
      o : bind
      type : none

  wordpress:
    name: wordpress
    driver: local
    driver_opts:
      device: /home/librahim/data/wordpress
      o : bind
      type : none
  
  vol_one:
    name: vol_one
    driver: local
    driver_opts:
      device: /
      o : bind
      type : none
    
  vol_two:
    name: vol_two
    driver: local
    driver_opts:
      device: /var/run
      o : bind
      type : none
    
  vol_thri:
    name: vol_thri
    driver: local
    driver_opts:
      device: /sys
      o : bind
      type : none
    
  vol_foor:
    name: vol_foor
    driver: local
    driver_opts:
      device: /var/lib/docker/
      o : bind
      type : none

  vol_five:
    name: vol_five
    driver: local
    driver_opts:
      device: /sys/fs/cgroup
      o : bind
      type : none
    
  vol_proc:
    name: vol_proc
    driver: local
    driver_opts:
      device: /proc
      o : bind
      type : none

networks:
  incepnet:
    driver: bridge
