


services:
  nginx:
    image: nginx:librahim
    container_name: nginx
    build: ./requirements/nginx
    ports:
      - "443:443"
    depends_on:
      - wordpress
    volumes:
      - wordpress:/var/www/wordpress
    networks:
      - incepnet
    restart: always


  mariadb:
    image: mariadb:librahim
    container_name: mariadb
    build: ./requirements/mariadb
    volumes:
      - mariadb:/var/lib/mysql
    env_file :
      - .env
    networks :
      - incepnet
    restart: always



  wordpress:
    image: wordpress:librahim
    container_name: wordpress
    build: ./requirements/wordpress
    depends_on:
      - mariadb
    volumes:
      - wordpress:/var/www/wordpress
    env_file :
      - .env
    networks:
      - incepnet
    restart: always



volumes:
  mariadb:
    name: mariadb
    driver: local
    driver_opts:
      device: /home/librahim/data/mariadb
      o : bind
      type : none
  wordpress:
    name: wordpress
    driver: local
    driver_opts:
      device: /home/librahim/data/wordpress
      o : bind
      type : none



networks:
  incepnet:
    driver: bridge